# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadata',
            options={'verbose_name_plural': 'Metadata'},
        ),
    ]
